In [1]:
import numpy as np
import pImpactR as impact
from copy import deepcopy as copy
input_fname = 'test_IOTA.in'
np.set_printoptions(precision=3)

# Prepare Beam and Lattice

In [2]:
beam, lattice0 = impact.readInputFile(input_fname)

reading ImpactZ input file (test_IOTA.in)
  : mpi task info .............................done
  : simulation control parameters .............done
  : space charge field solver, mesh info ......done
  : dist-type,restart,subcycle,#of state ......done
  : Multiple Charge State info ................done
  : particle distribution info ................done
  : beam reference orbit info .................done
  : converting impact dist to twiss param......done
  : lattice info ..............................done


In [3]:
beam.nCore_y=4
beam.nCore_z=2
beam.n_particles=2**13
beam.current=0.1
dist = beam.distribution
dist.distribution_type = 'Waterbag'
dist.mode = 'twiss'
dist.betx = 12.2
dist.alfx = 1.4
dist.emitx = 2.3e-6
dist.bety = 18.2
dist.alfy = -2.4
dist.emity = 3.2e-6
dist.betz = 200
dist.alfz = 0
dist.emitz = 0.0005
lattice = [impact.getElem('loop'),
           impact.getElem('write_raw_ptcl'),
           0,
           impact.getElem('write_raw_ptcl'),
           0,
           impact.getElem('write_raw_ptcl')]
lattice[0].nturn = 1
lattice[1].file_id = 1001
lattice[3].file_id = 1002
lattice[5].file_id = 1003


ke = beam.kinetic_energy
mass = beam.mass
freq = beam.frequency

# 1. Drift

In [4]:
elemF = impact.getElem('drift')
elemF.length = 0.02
elemF.n_sckick = 20
elemF.n_map = 1

elemB = copy(elemF)
elemB.length =-elemF.length

lattice[2] = elemF
lattice[4] = elemB

impact.writeInputFile(beam,lattice);

In [5]:
impact.run(beam,order=3)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 0.000e+00  1.735e-18  0.000e+00  0.000e+00 -2.220e-16  0.000e+00]
 [-1.735e-17  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [-1.735e-18  0.000e+00  0.000e+00  0.000e+00  1.388e-17  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  1.301e-18  0.000e+00  0.000e+00]
 [-3.469e-17  0.000e+00 -1.735e-18  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  8.674e-18  0.000e+00  0.000e+00  1.137e-13]
 [ 4.857e-17  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]]


In [6]:
impact.run(beam,order=1)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 0.000e+00  2.602e-18  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 1.735e-17  0.000e+00 -1.735e-18  0.000e+00  0.000e+00  0.000e+00]
 [-1.735e-18  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -1.735e-17 -8.674e-19  0.000e+00  0.000e+00]
 [-1.388e-17  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 1.735e-18  0.000e+00 -1.301e-18  0.000e+00 -3.469e-17  0.000e+00]
 [ 0.000e+00  0.000e+00 -8.674e-18  0.000e+00  0.000e+00  1.137e-13]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]]


# 2. Quad

In [7]:
elemF = impact.getElem('quad')
elemF.length = 0.02
elemF.n_sckick = 20
elemF.n_map = 1
elemF.B1 = 15.0

elemB = copy(elemF)
elemB.length =-elemF.length

lattice[2] = elemF
lattice[4] = elemB

impact.writeInputFile(beam,lattice);

In [8]:
impact.run(beam,order=3)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[-1.735e-17 -6.505e-18 -2.776e-17  3.357e-16  4.441e-16  0.000e+00]
 [-4.857e-17  1.648e-17  8.327e-17  1.299e-16  0.000e+00  0.000e+00]
 [-2.949e-17 -2.819e-18 -1.388e-17 -4.337e-18  6.939e-18  0.000e+00]
 [ 5.031e-17  3.036e-18 -1.249e-16 -8.023e-17  0.000e+00  0.000e+00]
 [-3.469e-17  6.939e-18  2.429e-17  9.714e-17  0.000e+00  0.000e+00]
 [ 3.296e-17 -1.301e-17 -1.258e-17  2.255e-17  1.388e-17  0.000e+00]
 [ 9.714e-17 -1.735e-17  3.643e-17 -3.860e-17  0.000e+00  1.137e-13]
 [ 2.776e-17 -1.735e-18  2.255e-17 -5.421e-20  0.000e+00  0.000e+00]]


In [9]:
impact.run(beam,order=1)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[-1.735e-17 -6.505e-18 -2.776e-17  3.357e-16  4.441e-16  0.000e+00]
 [-4.857e-17  1.648e-17  8.327e-17  1.299e-16  0.000e+00  0.000e+00]
 [-2.949e-17 -2.819e-18 -1.388e-17 -4.337e-18  6.939e-18  0.000e+00]
 [ 5.031e-17  3.036e-18 -1.249e-16 -8.023e-17  0.000e+00  0.000e+00]
 [-3.469e-17  6.939e-18  2.429e-17  9.714e-17  0.000e+00  0.000e+00]
 [ 3.296e-17 -1.301e-17 -1.258e-17  2.255e-17  1.388e-17  0.000e+00]
 [ 9.714e-17 -1.735e-17  3.643e-17 -3.860e-17  0.000e+00  1.137e-13]
 [ 2.776e-17 -1.735e-18  2.255e-17 -5.421e-20  0.000e+00  0.000e+00]]


# 3. Sextupole

In [10]:
for i in range(len(lattice0)):
    if lattice0[i].type == 'multipole_thin':
        break
lattice0[i]


 KL_dipole: 0.0
   KL_quad: 0.0
   KL_sext: 0.15
    KL_oct: 0.0
   KL_deca: 0.0
 KL_dodeca: 0.0
      type: 'multipole_thin'

In [11]:
elemF = lattice0[i]
elemF.KL_sext = 1000.0

elemB = copy(elemF)
elemB.KL_sext =-elemF.KL_sext

lattice[2] = elemF
lattice[4] = elemB

impact.writeInputFile(beam,lattice);
impact.run(beam,order=3)

0

In [12]:
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 0.000e+00  2.602e-18  0.000e+00 -6.939e-18  0.000e+00  0.000e+00]
 [ 0.000e+00 -6.939e-18  0.000e+00 -2.342e-17  0.000e+00  0.000e+00]
 [ 0.000e+00  6.505e-19  0.000e+00  3.903e-18  0.000e+00  0.000e+00]
 [ 0.000e+00  6.505e-19  0.000e+00 -3.903e-18  0.000e+00  0.000e+00]
 [ 0.000e+00  3.036e-17  0.000e+00 -1.735e-18  0.000e+00  0.000e+00]
 [ 0.000e+00  3.469e-18  0.000e+00 -2.331e-18  0.000e+00  0.000e+00]
 [ 0.000e+00  6.072e-18  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  6.939e-18  0.000e+00  5.123e-18  0.000e+00  0.000e+00]]


# 4. Dipole

In [13]:
for i in range(len(lattice0)):
    if lattice0[i].type == 'dipole':
        break
lattice0[i]


                   length: 0.7330382858 [m]
                 n_sckick: 10 [1]
                    n_map: 20 [1]
            bending_angle: 1.047197551 [rad]
                       k1: 0.0
                  file_id: 350
              pipe_radius: 0.058 [m]
           entrance_angle: 0.0 [rad]
               exit_angle: 0.0 [rad]
       entrance_curvature: 0.0 [rad]
           exit_curvature: 0.0 [rad]
 fringe_field_integration: 0.5 [1]
                     type: 'dipole'

### negative length, bending angle and FINT

In [14]:
elemF = copy(lattice0[i])

elemB = copy(elemF)
elemB.length = -elemF.length
elemB.bending_angle = -elemF.bending_angle
elemB.fringe_field_integration = -elemF.fringe_field_integration
elemB.entrance_angle = -elemF.exit_angle
elemB.exit_angle     = -elemF.entrance_angle

lattice[2] = elemF
lattice[4] = elemB

impact.writeInputFile(beam,lattice);

In [15]:
impact.run(beam,order=3)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 2.771e-07 -9.177e-07 -1.105e-07  5.994e-07 -1.815e-05  0.000e+00]
 [-1.268e-07  4.949e-07  1.195e-07 -3.046e-07  1.925e-05  0.000e+00]
 [ 1.004e-07 -3.516e-07 -1.480e-07  5.150e-07 -1.219e-05  0.000e+00]
 [-1.062e-07  3.649e-07  1.829e-07 -5.376e-07  1.790e-05  0.000e+00]
 [ 1.969e-07 -6.384e-07  8.873e-09  9.583e-08 -2.487e-05  0.000e+00]
 [ 7.402e-08 -2.679e-07  1.449e-10 -2.631e-08 -9.994e-06  0.000e+00]
 [ 1.787e-07 -5.858e-07 -3.051e-08  1.847e-07 -2.359e-05  1.137e-13]
 [-1.409e-07  7.011e-07 -3.441e-08  6.339e-08  3.961e-06  0.000e+00]]


In [16]:
impact.run(beam,order=1)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 2.683e-07 -8.600e-07 -2.017e-07  6.688e-07 -3.885e-05  0.000e+00]
 [-1.384e-07  5.065e-07  8.199e-08 -2.541e-07  1.834e-05  0.000e+00]
 [ 9.705e-08 -3.233e-07 -1.668e-07  5.561e-07 -1.365e-05  0.000e+00]
 [-1.196e-07  4.237e-07  1.504e-07 -4.968e-07  1.601e-05  0.000e+00]
 [ 1.825e-07 -6.435e-07 -5.090e-08  1.613e-07 -2.478e-05  0.000e+00]
 [ 6.760e-08 -2.513e-07  2.774e-09 -2.634e-08 -9.021e-06  0.000e+00]
 [ 1.640e-07 -5.845e-07 -6.382e-08  2.146e-07 -2.210e-05  1.137e-13]
 [-1.744e-07  6.271e-07 -1.392e-08  4.820e-08  2.338e-05  0.000e+00]]


# 5. Nonlinear Insert

In [17]:
for i in range(len(lattice0)):
    if lattice0[i].type == 'nonlinear_insert':
        break
lattice0[i]


             length: 1.8 [m]
           n_sckick: 96 [1]
              n_map: 5 [1]
         strength_t: 0.4
 transverse_scale_c: 0.01
        pipe_radius: 10.0 [m]
       tune_advance: 0.3034496449165134
               type: 'nonlinear_insert'

In [18]:
elemF = lattice0[i]

elemB = copy(elemF)
elemB.length =-elemF.length

lattice[2] = elemF
lattice[4] = elemB

impact.writeInputFile(beam,lattice);

In [19]:
impact.run(beam,order=3)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 0.000e+00 -6.505e-18 -9.714e-17  8.240e-18  1.221e-15  0.000e+00]
 [ 0.000e+00  2.602e-18  2.429e-17 -9.758e-18  1.998e-15  0.000e+00]
 [-1.735e-18 -3.036e-18  6.939e-18 -3.036e-18  3.331e-16  0.000e+00]
 [ 1.388e-17 -3.144e-18  0.000e+00  6.072e-18 -1.995e-16  0.000e+00]
 [-3.469e-17 -2.602e-18 -1.561e-17  2.602e-18  0.000e+00  0.000e+00]
 [ 1.908e-17 -1.240e-16  1.128e-17  2.803e-17  1.735e-16  0.000e+00]
 [-3.469e-17 -8.674e-18 -1.908e-17  3.903e-18  1.110e-16  1.137e-13]
 [ 0.000e+00 -6.072e-18 -6.505e-18 -1.355e-20  6.106e-16  0.000e+00]]


In [20]:
impact.run(beam,order=1)

pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 0.000e+00 -2.602e-18 -1.284e-16 -5.638e-18 -1.110e-16  0.000e+00]
 [ 1.735e-17 -9.541e-18 -1.214e-17 -7.156e-18  0.000e+00  0.000e+00]
 [-6.939e-17  6.072e-18  2.082e-17 -1.258e-17 -1.388e-17  0.000e+00]
 [-5.031e-17  1.214e-17  3.469e-17  8.240e-18 -7.459e-17  0.000e+00]
 [-4.857e-17 -1.301e-18 -1.041e-17  1.735e-18  0.000e+00  0.000e+00]
 [-8.674e-18 -6.505e-17 -6.505e-18  1.344e-17 -2.082e-17  0.000e+00]
 [-6.245e-17  0.000e+00  2.082e-17 -3.036e-18  0.000e+00  1.137e-13]
 [ 2.776e-17 -1.735e-18 -6.505e-18  5.421e-19  3.608e-16  0.000e+00]]


# 6. Nonlinear Insert sliced

In [21]:
NL0 = impact.getElem('nonlinear_insert_sliced')

In [22]:
elemF = lattice0[i]

elemB = copy(elemF)
elemB.length =-elemF.length

lattice[2] = elemF
lattice[4] = elemB

impact.writeInputFile(beam,lattice);
impact.run(beam,order=3)

0

In [23]:
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 0.000e+00 -6.505e-18 -9.714e-17  8.240e-18  1.221e-15  0.000e+00]
 [ 0.000e+00  2.602e-18  2.429e-17 -9.758e-18  1.998e-15  0.000e+00]
 [-1.735e-18 -3.036e-18  6.939e-18 -3.036e-18  3.331e-16  0.000e+00]
 [ 1.388e-17 -3.144e-18  0.000e+00  6.072e-18 -1.995e-16  0.000e+00]
 [-3.469e-17 -2.602e-18 -1.561e-17  2.602e-18  0.000e+00  0.000e+00]
 [ 1.908e-17 -1.240e-16  1.128e-17  2.803e-17  1.735e-16  0.000e+00]
 [-3.469e-17 -8.674e-18 -1.908e-17  3.903e-18  1.110e-16  1.137e-13]
 [ 0.000e+00 -6.072e-18 -6.505e-18 -1.355e-20  6.106e-16  0.000e+00]]


In [24]:
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData1 = impact.readParticleData(1002,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:8,:6]-pData2[:8,:6])

[[ 0.000e+00 -6.505e-18 -9.714e-17  8.240e-18  1.221e-15  0.000e+00]
 [ 0.000e+00  2.602e-18  2.429e-17 -9.758e-18  1.998e-15  0.000e+00]
 [-1.735e-18 -3.036e-18  6.939e-18 -3.036e-18  3.331e-16  0.000e+00]
 [ 1.388e-17 -3.144e-18  0.000e+00  6.072e-18 -1.995e-16  0.000e+00]
 [-3.469e-17 -2.602e-18 -1.561e-17  2.602e-18  0.000e+00  0.000e+00]
 [ 1.908e-17 -1.240e-16  1.128e-17  2.803e-17  1.735e-16  0.000e+00]
 [-3.469e-17 -8.674e-18 -1.908e-17  3.903e-18  1.110e-16  1.137e-13]
 [ 0.000e+00 -6.072e-18 -6.505e-18 -1.355e-20  6.106e-16  0.000e+00]]
