In [1]:
import numpy as np
import pImpactR as impact
from copy import deepcopy as copy
import os
input_fname = 'test_IOTA.in'
np.set_printoptions(precision=3)

# Prepare Beam and Lattice

In [2]:
beam, lattice0 = impact.readInputFile(input_fname)

reading ImpactZ input file (test_IOTA.in)
  : mpi task info .............................done
  : simulation control parameters .............done
  : space charge field solver, mesh info ......done
  : dist-type,restart,subcycle,#of state ......done
  : Multiple Charge State info ................done
  : particle distribution info ................done
  : beam reference orbit info .................done
  : converting impact dist to twiss param......done
  : lattice info ..............................done


In [3]:
beam.nCore_y=1
beam.nCore_z=1
beam.n_particles=3
beam.current=0.0
dist = beam.distribution
dist.distribution_type = 'ReadFile'
lattice = [impact.getElem('loop_through_lattice'),
           impact.getElem('write_raw_ptcl'),
           0,
           impact.getElem('write_raw_ptcl'),
           0,
           impact.getElem('write_raw_ptcl')]
lattice[0].nturn = 1
lattice[1].file_id = 1001
lattice[3].file_id = 1002
lattice[5].file_id = 1003


ke = beam.kinetic_energy
mass = beam.mass
freq = beam.frequency

In [4]:
for i in range(len(lattice0)):
    if lattice0[i].type == 'dipole':
        break
elemF = copy(lattice0[i])
elemF.fringe_field_integration = 10000000.0

## x-amplitude

In [5]:
k=0
q_m = beam.multi_charge.q_m[0]
pTest = []
for i in range(5):
    pTest.append([1.0e-5*(10.0**i),0.0,0,0.0,0.0,0.0,q_m,0.0,k])

pTest = np.array(pTest)
ke = beam.kinetic_energy
mass = beam.mass
freq = beam.frequency
impact.writeParticleData(pTest, ke, mass, freq)

In [6]:
elemB = copy(elemF)
elemB.length = -elemF.length
elemB.bending_angle = -elemF.bending_angle
elemB.fringe_field_integration = -elemF.fringe_field_integration

lattice[2] = elemF
lattice[4] = elemB
impact.writeInputFile(beam,lattice)

input error <- sum(beam.multi_charge.n_particles) not qual to beam.n_particles
  ... enforcing  beam.multi_charge.n_particles[0] to beam.n_particles
input error <- beam.multi_charge.current[0] not qual to beam.current
  ... enforcing  beam.multi_charge.current[0] to beam.current


###### MaryLie_order = 1

In [7]:
impact.run()
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:,:6]-pData2[:,:6])

[[ 6.776e-21  3.080e-21  0.000e+00  0.000e+00  3.543e-18  0.000e+00]
 [ 6.776e-20  2.029e-20  0.000e+00  0.000e+00  7.765e-18  0.000e+00]
 [ 6.505e-19  3.479e-19  0.000e+00  0.000e+00 -4.348e-17  0.000e+00]
 [ 5.204e-18 -8.349e-19  0.000e+00  0.000e+00  2.684e-15  0.000e+00]
 [ 8.327e-17  1.929e-17  0.000e+00  0.000e+00  7.951e-16  0.000e+00]]


###### MaryLie_order = 2

In [8]:
os.system('xmain_dipoleF2')
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:,:6]-pData2[:,:6])

[[ 1.636e-17  6.895e-22  0.000e+00  0.000e+00  1.720e-18  0.000e+00]
 [ 1.635e-14  5.303e-19  0.000e+00  0.000e+00 -1.708e-16  0.000e+00]
 [ 1.635e-11  6.000e-15  0.000e+00  0.000e+00 -2.077e-12  0.000e+00]
 [ 1.639e-08  5.975e-11  0.000e+00  0.000e+00 -2.068e-08  0.000e+00]
 [ 1.670e-05  5.738e-07  0.000e+00  0.000e+00 -1.986e-04  0.000e+00]]


###### MaryLie_order = 3

In [9]:
os.system('xmain_dipoleF3')
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:,:6]-pData2[:,:6])

[[ 6.776e-21 -1.258e-22  0.000e+00  0.000e+00  1.128e-18  0.000e+00]
 [-2.575e-19 -5.442e-19  0.000e+00  0.000e+00  1.887e-16  0.000e+00]
 [-3.735e-15 -6.003e-15  0.000e+00  0.000e+00  2.075e-12  0.000e+00]
 [-3.737e-11 -6.003e-11  0.000e+00  0.000e+00  2.048e-08  0.000e+00]
 [-3.737e-07 -6.003e-07  0.000e+00  0.000e+00  1.781e-04  0.000e+00]]


## y-amplitude

In [10]:
pTest = []
for i in range(5):
    pTest.append([0.0,0.0,1.0e-5*(10.0**i),0.0,0.0,0.0,q_m,0.0,k])

pTest = np.array(pTest)
impact.writeParticleData(pTest, ke, mass, freq)

###### MaryLie_order = 1

In [11]:
impact.run()
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:,:6]-pData2[:,:6])

[[ 0.000e+00  0.000e+00 -2.202e-20  6.030e-19  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -1.044e-18  2.226e-17  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00 -2.385e-18  5.937e-17  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  1.908e-17 -4.275e-16  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  2.692e-15 -5.585e-14  0.000e+00  0.000e+00]]


###### MaryLie_order = 2

In [12]:
os.system('xmain_dipoleF2')
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:,:6]-pData2[:,:6])

[[ 1.501e-17  1.453e-17 -1.076e-14 -3.336e-18 -5.031e-15  0.000e+00]
 [ 1.501e-13  1.453e-13 -1.076e-11 -5.425e-16 -5.031e-11  0.000e+00]
 [ 1.501e-09  1.453e-09 -1.075e-08 -6.727e-11 -5.030e-07  0.000e+00]
 [ 1.546e-05  1.432e-05 -1.043e-05 -5.462e-06 -4.956e-03  0.000e+00]
 [ 1.104e+00  9.205e-02 -7.309e-01  1.448e+01 -3.186e+01  0.000e+00]]


###### MaryLie_order = 3

In [13]:
os.system('xmain_dipoleF3')
pData0 = impact.readParticleData(1001,ke,mass,freq)
pData2 = impact.readParticleData(1003,ke,mass,freq)
print(pData0[:,:6]-pData2[:,:6])

[[-2.680e-17 -5.096e-17 -1.135e-19  2.384e-18  1.764e-14  0.000e+00]
 [-2.680e-13 -5.096e-13 -2.062e-16  3.677e-15  1.764e-10  0.000e+00]
 [-2.680e-09 -5.097e-09 -2.042e-11  3.634e-10  1.765e-06  0.000e+00]
 [-2.691e-05 -5.175e-05 -1.969e-06  3.486e-05  1.879e-02  0.000e+00]
 [ 8.908e+01 -1.481e+01  1.763e+01 -1.211e+02  5.597e+05  0.000e+00]]
